name: Run Lint in Client

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run prefix lint
        working-directory: ./client
        run: npm run lint
